// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nju/quadra/quantra/data/StockBase.proto

package nju.quadra.quantra.data;

public final class StockBaseProtos {
  private StockBaseProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StockBaseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StockBase)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> 
        getInfoList();
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getInfo(int index);
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    int getInfoCount();
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    java.util.List<? extends nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder> 
        getInfoOrBuilderList();
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder getInfoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code StockBase}
   */
  public  static final class StockBase extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:StockBase)
      StockBaseOrBuilder {
    // Use StockBase.newBuilder() to construct.
    private StockBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockBase() {
      info_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StockBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                info_ = new java.util.ArrayList<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              info_.add(
                  input.readMessage(nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = java.util.Collections.unmodifiableList(info_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nju.quadra.quantra.data.StockBaseProtos.StockBase.class, nju.quadra.quantra.data.StockBaseProtos.StockBase.Builder.class);
    }

    public interface StockInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:StockBase.StockInfo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional uint32 serial = 1;</code>
       */
      int getSerial();

      /**
       * <code>optional string date = 2;</code>
       */
      java.lang.String getDate();
      /**
       * <code>optional string date = 2;</code>
       */
      com.google.protobuf.ByteString
          getDateBytes();

      /**
       * <code>optional float open = 3;</code>
       */
      float getOpen();

      /**
       * <code>optional float high = 4;</code>
       */
      float getHigh();

      /**
       * <code>optional float low = 5;</code>
       */
      float getLow();

      /**
       * <code>optional float close = 6;</code>
       */
      float getClose();

      /**
       * <code>optional uint32 volume = 7;</code>
       */
      int getVolume();

      /**
       * <code>optional float adjClose = 8;</code>
       */
      float getAdjClose();

      /**
       * <code>optional uint32 code = 9;</code>
       */
      int getCode();

      /**
       * <code>optional string name = 10;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 10;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>optional string market = 11;</code>
       */
      java.lang.String getMarket();
      /**
       * <code>optional string market = 11;</code>
       */
      com.google.protobuf.ByteString
          getMarketBytes();

      /**
       * <code>optional string pinyin = 12;</code>
       */
      java.lang.String getPinyin();
      /**
       * <code>optional string pinyin = 12;</code>
       */
      com.google.protobuf.ByteString
          getPinyinBytes();
    }
    /**
     * Protobuf type {@code StockBase.StockInfo}
     */
    public  static final class StockInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:StockBase.StockInfo)
        StockInfoOrBuilder {
      // Use StockInfo.newBuilder() to construct.
      private StockInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private StockInfo() {
        serial_ = 0;
        date_ = "";
        open_ = 0F;
        high_ = 0F;
        low_ = 0F;
        close_ = 0F;
        volume_ = 0;
        adjClose_ = 0F;
        code_ = 0;
        name_ = "";
        market_ = "";
        pinyin_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private StockInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                serial_ = input.readUInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                date_ = s;
                break;
              }
              case 29: {

                open_ = input.readFloat();
                break;
              }
              case 37: {

                high_ = input.readFloat();
                break;
              }
              case 45: {

                low_ = input.readFloat();
                break;
              }
              case 53: {

                close_ = input.readFloat();
                break;
              }
              case 56: {

                volume_ = input.readUInt32();
                break;
              }
              case 69: {

                adjClose_ = input.readFloat();
                break;
              }
              case 72: {

                code_ = input.readUInt32();
                break;
              }
              case 82: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 90: {
                java.lang.String s = input.readStringRequireUtf8();

                market_ = s;
                break;
              }
              case 98: {
                java.lang.String s = input.readStringRequireUtf8();

                pinyin_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_StockInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_StockInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.class, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder.class);
      }

      public static final int SERIAL_FIELD_NUMBER = 1;
      private int serial_;
      /**
       * <code>optional uint32 serial = 1;</code>
       */
      public int getSerial() {
        return serial_;
      }

      public static final int DATE_FIELD_NUMBER = 2;
      private volatile java.lang.Object date_;
      /**
       * <code>optional string date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        }
      }
      /**
       * <code>optional string date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int OPEN_FIELD_NUMBER = 3;
      private float open_;
      /**
       * <code>optional float open = 3;</code>
       */
      public float getOpen() {
        return open_;
      }

      public static final int HIGH_FIELD_NUMBER = 4;
      private float high_;
      /**
       * <code>optional float high = 4;</code>
       */
      public float getHigh() {
        return high_;
      }

      public static final int LOW_FIELD_NUMBER = 5;
      private float low_;
      /**
       * <code>optional float low = 5;</code>
       */
      public float getLow() {
        return low_;
      }

      public static final int CLOSE_FIELD_NUMBER = 6;
      private float close_;
      /**
       * <code>optional float close = 6;</code>
       */
      public float getClose() {
        return close_;
      }

      public static final int VOLUME_FIELD_NUMBER = 7;
      private int volume_;
      /**
       * <code>optional uint32 volume = 7;</code>
       */
      public int getVolume() {
        return volume_;
      }

      public static final int ADJCLOSE_FIELD_NUMBER = 8;
      private float adjClose_;
      /**
       * <code>optional float adjClose = 8;</code>
       */
      public float getAdjClose() {
        return adjClose_;
      }

      public static final int CODE_FIELD_NUMBER = 9;
      private int code_;
      /**
       * <code>optional uint32 code = 9;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int NAME_FIELD_NUMBER = 10;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 10;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 10;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MARKET_FIELD_NUMBER = 11;
      private volatile java.lang.Object market_;
      /**
       * <code>optional string market = 11;</code>
       */
      public java.lang.String getMarket() {
        java.lang.Object ref = market_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          market_ = s;
          return s;
        }
      }
      /**
       * <code>optional string market = 11;</code>
       */
      public com.google.protobuf.ByteString
          getMarketBytes() {
        java.lang.Object ref = market_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          market_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PINYIN_FIELD_NUMBER = 12;
      private volatile java.lang.Object pinyin_;
      /**
       * <code>optional string pinyin = 12;</code>
       */
      public java.lang.String getPinyin() {
        java.lang.Object ref = pinyin_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pinyin_ = s;
          return s;
        }
      }
      /**
       * <code>optional string pinyin = 12;</code>
       */
      public com.google.protobuf.ByteString
          getPinyinBytes() {
        java.lang.Object ref = pinyin_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pinyin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (serial_ != 0) {
          output.writeUInt32(1, serial_);
        }
        if (!getDateBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
        }
        if (open_ != 0F) {
          output.writeFloat(3, open_);
        }
        if (high_ != 0F) {
          output.writeFloat(4, high_);
        }
        if (low_ != 0F) {
          output.writeFloat(5, low_);
        }
        if (close_ != 0F) {
          output.writeFloat(6, close_);
        }
        if (volume_ != 0) {
          output.writeUInt32(7, volume_);
        }
        if (adjClose_ != 0F) {
          output.writeFloat(8, adjClose_);
        }
        if (code_ != 0) {
          output.writeUInt32(9, code_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 10, name_);
        }
        if (!getMarketBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 11, market_);
        }
        if (!getPinyinBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 12, pinyin_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (serial_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, serial_);
        }
        if (!getDateBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
        }
        if (open_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(3, open_);
        }
        if (high_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, high_);
        }
        if (low_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, low_);
        }
        if (close_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(6, close_);
        }
        if (volume_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(7, volume_);
        }
        if (adjClose_ != 0F) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(8, adjClose_);
        }
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(9, code_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, name_);
        }
        if (!getMarketBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, market_);
        }
        if (!getPinyinBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, pinyin_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo)) {
          return super.equals(obj);
        }
        nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo other = (nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo) obj;

        boolean result = true;
        result = result && (getSerial()
            == other.getSerial());
        result = result && getDate()
            .equals(other.getDate());
        result = result && (
            java.lang.Float.floatToIntBits(getOpen())
            == java.lang.Float.floatToIntBits(
                other.getOpen()));
        result = result && (
            java.lang.Float.floatToIntBits(getHigh())
            == java.lang.Float.floatToIntBits(
                other.getHigh()));
        result = result && (
            java.lang.Float.floatToIntBits(getLow())
            == java.lang.Float.floatToIntBits(
                other.getLow()));
        result = result && (
            java.lang.Float.floatToIntBits(getClose())
            == java.lang.Float.floatToIntBits(
                other.getClose()));
        result = result && (getVolume()
            == other.getVolume());
        result = result && (
            java.lang.Float.floatToIntBits(getAdjClose())
            == java.lang.Float.floatToIntBits(
                other.getAdjClose()));
        result = result && (getCode()
            == other.getCode());
        result = result && getName()
            .equals(other.getName());
        result = result && getMarket()
            .equals(other.getMarket());
        result = result && getPinyin()
            .equals(other.getPinyin());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + SERIAL_FIELD_NUMBER;
        hash = (53 * hash) + getSerial();
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
        hash = (37 * hash) + OPEN_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getOpen());
        hash = (37 * hash) + HIGH_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getHigh());
        hash = (37 * hash) + LOW_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getLow());
        hash = (37 * hash) + CLOSE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getClose());
        hash = (37 * hash) + VOLUME_FIELD_NUMBER;
        hash = (53 * hash) + getVolume();
        hash = (37 * hash) + ADJCLOSE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getAdjClose());
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + MARKET_FIELD_NUMBER;
        hash = (53 * hash) + getMarket().hashCode();
        hash = (37 * hash) + PINYIN_FIELD_NUMBER;
        hash = (53 * hash) + getPinyin().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code StockBase.StockInfo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:StockBase.StockInfo)
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_StockInfo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_StockInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.class, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder.class);
        }

        // Construct using nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          serial_ = 0;

          date_ = "";

          open_ = 0F;

          high_ = 0F;

          low_ = 0F;

          close_ = 0F;

          volume_ = 0;

          adjClose_ = 0F;

          code_ = 0;

          name_ = "";

          market_ = "";

          pinyin_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_StockInfo_descriptor;
        }

        public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getDefaultInstanceForType() {
          return nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.getDefaultInstance();
        }

        public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo build() {
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo buildPartial() {
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo result = new nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo(this);
          result.serial_ = serial_;
          result.date_ = date_;
          result.open_ = open_;
          result.high_ = high_;
          result.low_ = low_;
          result.close_ = close_;
          result.volume_ = volume_;
          result.adjClose_ = adjClose_;
          result.code_ = code_;
          result.name_ = name_;
          result.market_ = market_;
          result.pinyin_ = pinyin_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo) {
            return mergeFrom((nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo other) {
          if (other == nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.getDefaultInstance()) return this;
          if (other.getSerial() != 0) {
            setSerial(other.getSerial());
          }
          if (!other.getDate().isEmpty()) {
            date_ = other.date_;
            onChanged();
          }
          if (other.getOpen() != 0F) {
            setOpen(other.getOpen());
          }
          if (other.getHigh() != 0F) {
            setHigh(other.getHigh());
          }
          if (other.getLow() != 0F) {
            setLow(other.getLow());
          }
          if (other.getClose() != 0F) {
            setClose(other.getClose());
          }
          if (other.getVolume() != 0) {
            setVolume(other.getVolume());
          }
          if (other.getAdjClose() != 0F) {
            setAdjClose(other.getAdjClose());
          }
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getMarket().isEmpty()) {
            market_ = other.market_;
            onChanged();
          }
          if (!other.getPinyin().isEmpty()) {
            pinyin_ = other.pinyin_;
            onChanged();
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int serial_ ;
        /**
         * <code>optional uint32 serial = 1;</code>
         */
        public int getSerial() {
          return serial_;
        }
        /**
         * <code>optional uint32 serial = 1;</code>
         */
        public Builder setSerial(int value) {
          
          serial_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 serial = 1;</code>
         */
        public Builder clearSerial() {
          
          serial_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object date_ = "";
        /**
         * <code>optional string date = 2;</code>
         */
        public java.lang.String getDate() {
          java.lang.Object ref = date_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            date_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string date = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDateBytes() {
          java.lang.Object ref = date_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            date_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string date = 2;</code>
         */
        public Builder setDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          date_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string date = 2;</code>
         */
        public Builder clearDate() {
          
          date_ = getDefaultInstance().getDate();
          onChanged();
          return this;
        }
        /**
         * <code>optional string date = 2;</code>
         */
        public Builder setDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          date_ = value;
          onChanged();
          return this;
        }

        private float open_ ;
        /**
         * <code>optional float open = 3;</code>
         */
        public float getOpen() {
          return open_;
        }
        /**
         * <code>optional float open = 3;</code>
         */
        public Builder setOpen(float value) {
          
          open_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float open = 3;</code>
         */
        public Builder clearOpen() {
          
          open_ = 0F;
          onChanged();
          return this;
        }

        private float high_ ;
        /**
         * <code>optional float high = 4;</code>
         */
        public float getHigh() {
          return high_;
        }
        /**
         * <code>optional float high = 4;</code>
         */
        public Builder setHigh(float value) {
          
          high_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float high = 4;</code>
         */
        public Builder clearHigh() {
          
          high_ = 0F;
          onChanged();
          return this;
        }

        private float low_ ;
        /**
         * <code>optional float low = 5;</code>
         */
        public float getLow() {
          return low_;
        }
        /**
         * <code>optional float low = 5;</code>
         */
        public Builder setLow(float value) {
          
          low_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float low = 5;</code>
         */
        public Builder clearLow() {
          
          low_ = 0F;
          onChanged();
          return this;
        }

        private float close_ ;
        /**
         * <code>optional float close = 6;</code>
         */
        public float getClose() {
          return close_;
        }
        /**
         * <code>optional float close = 6;</code>
         */
        public Builder setClose(float value) {
          
          close_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float close = 6;</code>
         */
        public Builder clearClose() {
          
          close_ = 0F;
          onChanged();
          return this;
        }

        private int volume_ ;
        /**
         * <code>optional uint32 volume = 7;</code>
         */
        public int getVolume() {
          return volume_;
        }
        /**
         * <code>optional uint32 volume = 7;</code>
         */
        public Builder setVolume(int value) {
          
          volume_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 volume = 7;</code>
         */
        public Builder clearVolume() {
          
          volume_ = 0;
          onChanged();
          return this;
        }

        private float adjClose_ ;
        /**
         * <code>optional float adjClose = 8;</code>
         */
        public float getAdjClose() {
          return adjClose_;
        }
        /**
         * <code>optional float adjClose = 8;</code>
         */
        public Builder setAdjClose(float value) {
          
          adjClose_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float adjClose = 8;</code>
         */
        public Builder clearAdjClose() {
          
          adjClose_ = 0F;
          onChanged();
          return this;
        }

        private int code_ ;
        /**
         * <code>optional uint32 code = 9;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <code>optional uint32 code = 9;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 code = 9;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 10;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 10;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 10;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 10;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 10;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object market_ = "";
        /**
         * <code>optional string market = 11;</code>
         */
        public java.lang.String getMarket() {
          java.lang.Object ref = market_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            market_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string market = 11;</code>
         */
        public com.google.protobuf.ByteString
            getMarketBytes() {
          java.lang.Object ref = market_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            market_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string market = 11;</code>
         */
        public Builder setMarket(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          market_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string market = 11;</code>
         */
        public Builder clearMarket() {
          
          market_ = getDefaultInstance().getMarket();
          onChanged();
          return this;
        }
        /**
         * <code>optional string market = 11;</code>
         */
        public Builder setMarketBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          market_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object pinyin_ = "";
        /**
         * <code>optional string pinyin = 12;</code>
         */
        public java.lang.String getPinyin() {
          java.lang.Object ref = pinyin_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            pinyin_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string pinyin = 12;</code>
         */
        public com.google.protobuf.ByteString
            getPinyinBytes() {
          java.lang.Object ref = pinyin_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            pinyin_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string pinyin = 12;</code>
         */
        public Builder setPinyin(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          pinyin_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string pinyin = 12;</code>
         */
        public Builder clearPinyin() {
          
          pinyin_ = getDefaultInstance().getPinyin();
          onChanged();
          return this;
        }
        /**
         * <code>optional string pinyin = 12;</code>
         */
        public Builder setPinyinBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          pinyin_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:StockBase.StockInfo)
      }

      // @@protoc_insertion_point(class_scope:StockBase.StockInfo)
      private static final nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo();
      }

      public static nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<StockInfo>
          PARSER = new com.google.protobuf.AbstractParser<StockInfo>() {
        public StockInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new StockInfo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<StockInfo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<StockInfo> getParserForType() {
        return PARSER;
      }

      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int INFO_FIELD_NUMBER = 1;
    private java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> info_;
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    public java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> getInfoList() {
      return info_;
    }
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    public java.util.List<? extends nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder> 
        getInfoOrBuilderList() {
      return info_;
    }
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated .StockBase.StockInfo info = 1;</code>
     */
    public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(1, info_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, info_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nju.quadra.quantra.data.StockBaseProtos.StockBase)) {
        return super.equals(obj);
      }
      nju.quadra.quantra.data.StockBaseProtos.StockBase other = (nju.quadra.quantra.data.StockBaseProtos.StockBase) obj;

      boolean result = true;
      result = result && getInfoList()
          .equals(other.getInfoList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getInfoCount() > 0) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nju.quadra.quantra.data.StockBaseProtos.StockBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nju.quadra.quantra.data.StockBaseProtos.StockBase prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StockBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StockBase)
        nju.quadra.quantra.data.StockBaseProtos.StockBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nju.quadra.quantra.data.StockBaseProtos.StockBase.class, nju.quadra.quantra.data.StockBaseProtos.StockBase.Builder.class);
      }

      // Construct using nju.quadra.quantra.data.StockBaseProtos.StockBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          infoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nju.quadra.quantra.data.StockBaseProtos.internal_static_StockBase_descriptor;
      }

      public nju.quadra.quantra.data.StockBaseProtos.StockBase getDefaultInstanceForType() {
        return nju.quadra.quantra.data.StockBaseProtos.StockBase.getDefaultInstance();
      }

      public nju.quadra.quantra.data.StockBaseProtos.StockBase build() {
        nju.quadra.quantra.data.StockBaseProtos.StockBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public nju.quadra.quantra.data.StockBaseProtos.StockBase buildPartial() {
        nju.quadra.quantra.data.StockBaseProtos.StockBase result = new nju.quadra.quantra.data.StockBaseProtos.StockBase(this);
        int from_bitField0_ = bitField0_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nju.quadra.quantra.data.StockBaseProtos.StockBase) {
          return mergeFrom((nju.quadra.quantra.data.StockBaseProtos.StockBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nju.quadra.quantra.data.StockBaseProtos.StockBase other) {
        if (other == nju.quadra.quantra.data.StockBaseProtos.StockBase.getDefaultInstance()) return this;
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000001);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        nju.quadra.quantra.data.StockBaseProtos.StockBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nju.quadra.quantra.data.StockBaseProtos.StockBase) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          info_ = new java.util.ArrayList<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo>(info_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder> infoBuilder_;

      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder setInfo(
          int index, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder addInfo(nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder addInfo(
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder addInfo(
          int index, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder addAllInfo(
          java.lang.Iterable<? extends nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public java.util.List<? extends nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder> 
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .StockBase.StockInfo info = 1;</code>
       */
      public java.util.List<nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder> 
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfo.Builder, nju.quadra.quantra.data.StockBaseProtos.StockBase.StockInfoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:StockBase)
    }

    // @@protoc_insertion_point(class_scope:StockBase)
    private static final nju.quadra.quantra.data.StockBaseProtos.StockBase DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nju.quadra.quantra.data.StockBaseProtos.StockBase();
    }

    public static nju.quadra.quantra.data.StockBaseProtos.StockBase getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockBase>
        PARSER = new com.google.protobuf.AbstractParser<StockBase>() {
      public StockBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StockBase(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockBase> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockBase> getParserForType() {
      return PARSER;
    }

    public nju.quadra.quantra.data.StockBaseProtos.StockBase getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockBase_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockBase_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockBase_StockInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockBase_StockInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'nju/quadra/quantra/data/StockBase.prot" +
      "o\"\361\001\n\tStockBase\022\"\n\004info\030\001 \003(\0132\024.StockBas" +
      "e.StockInfo\032\277\001\n\tStockInfo\022\016\n\006serial\030\001 \001(" +
      "\r\022\014\n\004date\030\002 \001(\t\022\014\n\004open\030\003 \001(\002\022\014\n\004high\030\004 " +
      "\001(\002\022\013\n\003low\030\005 \001(\002\022\r\n\005close\030\006 \001(\002\022\016\n\006volum" +
      "e\030\007 \001(\r\022\020\n\010adjClose\030\010 \001(\002\022\014\n\004code\030\t \001(\r\022" +
      "\014\n\004name\030\n \001(\t\022\016\n\006market\030\013 \001(\t\022\016\n\006pinyin\030" +
      "\014 \001(\tB*\n\027nju.quadra.quantra.dataB\017StockB" +
      "aseProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_StockBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockBase_descriptor,
        new java.lang.String[] { "Info", });
    internal_static_StockBase_StockInfo_descriptor =
      internal_static_StockBase_descriptor.getNestedTypes().get(0);
    internal_static_StockBase_StockInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockBase_StockInfo_descriptor,
        new java.lang.String[] { "Serial", "Date", "Open", "High", "Low", "Close", "Volume", "AdjClose", "Code", "Name", "Market", "Pinyin", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
